SUPABASE_URL = "https://qwqgkrzssikerbmjincw.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3cWdrcnpzc2lrZXJibWppbmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzODI2NjgsImV4cCI6MjA3Njk1ODY2OH0.g7N07UjLaSJ0TAU60N8OtG57EYrnwTN5MydatTNbf4A"
